import numpy as np
import matplotlib.pyplot as plt
t=np.arange(-200,200,0.02)
a=np.arcsin(t)*(180/np.pi)
plt.subplot(1,5,1)
plt.plot(t,a)
plt.title('invsin')
plt.xlabel('time')
plt.ylabel('amplitude')
t=np.arange(-300,300,0.02)
a=np.arccos(t)*(180/np.pi)
plt.subplot(1,5,2)
plt.plot(t,a)
plt.title('invcos')
plt.xlabel('time')
plt.ylabel('amplitude')
t=np.arange(-100,100,0.02)
a=np.arctan(t)*(180/np.pi)
plt.subplot(1,5,3)
plt.plot(t,a)
plt.title('invtan')
plt.xlabel('time')
plt.ylabel('amplitude')
t=np.arange(-10,10,0.25)
a=np.sinc(2*np.pi*t)*(180/np.pi)
plt.subplot(1,5,4)
plt.plot(t,a)
plt.title('sinc pulse')
plt.xlabel('time')
plt.ylabel('amplitude')
f=float(input('enter the frequency'))
t=np.arange(0,10,0.25)
a=np.exp(2*np.pi*f*t)
plt.subplot(1,5,5)
plt.plot(t,a)
plt.title('exponential')
plt.xlabel('time')
plt.ylabel('amplitude')
plt.show()
